apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sandbox
  labels:
    app.kubernetes.io/name: loop-sandbox
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.sandbox.service.type }}
  ports:
    - port: {{ .Values.sandbox.service.port }}
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: loop-sandbox
    app.kubernetes.io/instance: {{ .Release.Name }}
